# Generated by Django 4.1.2 on 2022-11-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_examen_delete_answer_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('opcion_uno', models.CharField(max_length=100)),
                ('opcion_dos', models.CharField(max_length=100)),
                ('opcion_tres', models.CharField(max_length=100)),
                ('opcion_correcta', models.CharField(max_length=100)),
            ],
        ),
    ]
