from django.urls import include, path
from .views import (
    ClaveCreate,
    ClaveList,
    ClaveDetail,
    ClaveUpdate,
    ExamenCreate,
    ExamenList,
    ExamenDetail,
    ExamenUpdate,
    OpcionCreate,
    OpcionList,
    OpcionDetail,
    OpcionUpdate,
    PreguntaCreate,
    PreguntaList,
    PreguntaDetail,
    PreguntaUpdate,
    PreguntaOpcionCreate,
    PreguntaOpcionList,
    PreguntaOpcionDetail,
    PreguntaOpcionUpdate,
    RespuestaCreate,
    RespuestaList,
    RespuestaDetail,
    RespuestaUpdate,
    TurnoExamenCreate,
    TurnoExamenList,
    TurnoExamenDetail,
    TurnoExamenUpdate,
    TurnoRevisionCreate,
    TurnoRevisionList,
    TurnoRevisionDetail,
    TurnoRevisionUpdate,
    UsuarioCreate,
    UsuarioList,
    UsuarioDetail,
    UsuarioUpdate
)

urlpatterns = [
    path('clave/create/', ClaveCreate.as_view(), name='create-clave'),
    path('claves/', ClaveList.as_view()),
    path('clave/<int:pk>/', ClaveDetail.as_view(), name='retrieve-clave'),
    path('clave/update/<int:pk>/', ClaveUpdate.as_view(), name='update-clave'),
    # path('clave/delete/<int:pk>/', ClaveDelete.as_view(), name='delete-clave'),
    path('examen/create/', ExamenCreate.as_view(), name='create-examen'),
    path('examenes/', ExamenList.as_view()),
    path('examen/<int:pk>/', ExamenDetail.as_view(), name='retrieve-examen'),
    path('examen/update/<int:pk>/', ExamenUpdate.as_view(), name='update-examen'),
    # path('examen/delete/<int:pk>/', ExamenDelete.as_view(), name='delete-examen'),
    path('opcion/create/', OpcionCreate.as_view(), name='create-opcion'),
    path('opciones/', OpcionList.as_view()),
    path('opcion/<int:pk>/', OpcionDetail.as_view(), name='retrieve-opcion'),
    path('opcion/update/<int:pk>/', OpcionUpdate.as_view(), name='update-opcion'),
    # path('opcion/delete/<int:pk>/', OpcionDelete.as_view(), name='delete-opcion'),
    path('pregunta/create/', PreguntaCreate.as_view(), name='create-pregunta'),
    path('preguntas/', PreguntaList.as_view()),
    path('pregunta/<int:pk>/', PreguntaDetail.as_view(), name='retrieve-pregunta'),
    path('pregunta/update/<int:pk>/', PreguntaUpdate.as_view(), name='update-pregunta'),
    # path('pregunta/delete/<int:pk>/', PreguntaDelete.as_view(), name='delete-pregunta'),
    path('pregunta-opcion/create/', PreguntaOpcionCreate.as_view(), name='create-pregunta-opcion'),
    path('pregunta-opciones/', PreguntaOpcionList.as_view()),
    path('pregunta-opcion/<int:pk>/', PreguntaOpcionDetail.as_view(), name='retrieve-pregunta-opcion'),
    path('pregunta-opcion/update/<int:pk>/', PreguntaOpcionUpdate.as_view(), name='update-pregunta-opcion'),
    # path('pregunta-opcion/delete/<int:pk>/', PreguntaOpcionDelete.as_view(), name='delete-preguntaopcion'),
    path('respuesta/create/', RespuestaCreate.as_view(), name='create-respuesta'),
    path('respuestas/', RespuestaList.as_view()),
    path('respuesta/<int:pk>/', RespuestaDetail.as_view(), name='retrieve-respuesta'),
    path('respuesta/update/<int:pk>/', RespuestaUpdate.as_view(), name='update-respuesta'),
    # path('respuesta/delete/<int:pk>/', RespuestaDelete.as_view(), name='delete-respuesta'),
    path('turno-examen/create/', TurnoExamenCreate.as_view(), name='create-turno-examen'),
    path('turno-examenes/', TurnoExamenList.as_view()),
    path('turno-examen/<int:pk>/', TurnoExamenDetail.as_view(), name='retrieve-turno-examen'),
    path('turno-examen/update/<int:pk>/', TurnoExamenUpdate.as_view(), name='update-turno-examen'),
    # path('turno-examen/delete/<int:pk>/', TurnoExamenDelete.as_view(), name='delete-turno-examen'),
    path('turno-revision/create/', TurnoRevisionCreate.as_view(), name='create-turno-revision'),
    path('turno-revisiones/', TurnoRevisionList.as_view()),
    path('turno-revision/<int:pk>/', TurnoRevisionDetail.as_view(), name='retrieve-turno-revision'),
    path('turno-revision/update/<int:pk>/', TurnoRevisionUpdate.as_view(), name='update-turno-revision'),
    # path('turno-revision/delete/<int:pk>/', TurnoRevisionDelete.as_view(), name='delete-turno-revision'),
    path('usuario/create/', UsuarioCreate.as_view(), name='create-usuario'),
    path('usuarios/', UsuarioList.as_view()),
    path('usuario/<int:pk>/', UsuarioDetail.as_view(), name='retrieve-usuario'),
    path('usuario/update/<int:pk>/', UsuarioUpdate.as_view(), name='update-usuario'),
    # path('usuario/delete/<int:pk>/', UsuarioDelete.as_view(), name='delete-usuario'),
]