# Generated by Django 4.1.2 on 2022-11-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id_clave', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('es_valida', models.BooleanField()),
            ],
            options={
                'db_table': 'clave',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'opcion',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('habilitado', models.BooleanField()),
                ('anteojos', models.BooleanField()),
                ('nombre_usuario', models.TextField()),
                ('contrasenia', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PreguntaOpcion',
            fields=[
                ('id_pregunta', models.OneToOneField(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exam.pregunta')),
                ('opcion_correcta', models.BooleanField()),
                ('id_opcion', models.ForeignKey(db_column='id_opcion', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.opcion')),
            ],
            options={
                'db_table': 'pregunta_opcion',
                'unique_together': {('id_pregunta', 'id_opcion')},
            },
        ),
        migrations.CreateModel(
            name='TurnoRevision',
            fields=[
                ('id_turno_revision', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.usuario')),
            ],
            options={
                'db_table': 'turno_revision',
            },
        ),
        migrations.CreateModel(
            name='TurnoExamen',
            fields=[
                ('id_turno_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.usuario')),
            ],
            options={
                'db_table': 'turno_examen',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('realizado', models.BooleanField()),
                ('id_clave', models.ForeignKey(db_column='id_clave', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.clave')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.usuario')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_examen', models.OneToOneField(db_column='id_examen', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='exam.examen')),
                ('id_opcion', models.IntegerField()),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='exam.preguntaopcion')),
            ],
            options={
                'db_table': 'respuesta',
                'unique_together': {('id_examen', 'id_pregunta', 'id_opcion')},
            },
        ),
    ]
